"""users and roles

Revision ID: 38590da651d
Revises: None
Create Date: 2014-02-25 00:24:40.813269

"""

# revision identifiers, used by Alembic.
revision = '38590da651d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column(
                        'password', sa.String(length=255), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('last_login_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'current_login_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'last_login_ip', sa.String(length=255), nullable=True),
                    sa.Column(
                        'current_login_ip', sa.String(length=255), nullable=True),
                    sa.Column('login_count', sa.Integer(), nullable=True),
                    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'first_name', sa.String(length=50), nullable=True),
                    sa.Column(
                        'last_name', sa.String(length=50), nullable=True),
                    sa.Column('nickname', sa.String(length=50), nullable=True),
                    sa.Column(
                        'home_phone', sa.String(length=50), nullable=True),
                    sa.Column(
                        'cell_phone', sa.String(length=50), nullable=True),
                    sa.Column('emergency_contact_phone',
                              sa.String(length=50), nullable=True),
                    sa.Column('emergency_contact_name',
                              sa.String(length=255), nullable=True),
                    sa.Column('birthday', sa.Date(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default='CURRENT_TIMESTAMP', nullable=True),
                    sa.Column('address', sa.String(length=50), nullable=True),
                    sa.Column('address2', sa.String(length=50), nullable=True),
                    sa.Column('city', sa.String(length=50), nullable=True),
                    sa.Column('state', sa.String(length=2), nullable=True),
                    sa.Column('zip_code', sa.String(length=7), nullable=True),
                    sa.Column('freshbooks_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Unicode(length=80), nullable=True),
                    sa.Column(
                        'description', sa.Unicode(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles_users',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('role')
    op.drop_table('user')
    # end Alembic commands ###
