APP_NAME = "ATXHS User Dashboard"

# SERVER_NAME = 'localhost:5000'
DEBUG = True
SECRET_KEY = 'SERIOUSLY REPLACE THIS WITH RANDOM BYTES'
SQLALCHEMY_DATABASE_URI = 'sqlite://'

FRESHBOOKS_URL = 'whatevs.freshbooks.com'
FRESHBOOKS_TOKEN = 'fjkdlsfjdsklfjdsklfjds'
FRESHBOOKS_USER_AGENT = 'ATX Hackerspace Payments'

# Security config
SECURITY_CHANGABLE = True
SECURITY_CONFIRMABLE = True
SECURITY_RECOVERABLE = True
SECURITY_REGISTERABLE = True
SECURITY_TRACKABLE = True

SECURITY_FLASH_MESSAGES = 'ldap_sha256_crypt'
SECURITY_PASSWORD_SALT = 'SET THIS TO SOMETHING ELSE IN PRODUCTION'
